[package]
name = "kernel"
version = "0.1.0"
authors = ["Dan Cross <cross@gajendra.net>"]
edition = "2021"

[dependencies]
bitflags = "*"
seq-macro = "*"
static_assertions = "*"
syslib = { path = "../syslib" }
zerocopy = "*"
